[package]
name = "turing-lcd"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Driver for Turing Smart Screen / UsbMonitor rev. A USB-C IPS displays"

[dependencies]
serialport = { version = "4.7", default-features = false }
fontdue = "0.9"
